name: flutter_seo
description: "Flutter SEO package"
version: 0.0.1
homepage: 'https://github.com/jinhan38/flutter_seo'
publish_to: 'https://pub.dev/publishers/jinhan38.com'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

